name: Python CI with Ruff and Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Add Poetry to PATH
      - name: Add Poetry to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install --no-root

      # Run Ruff for linting
      - name: Run Ruff
        run: |
          poetry run ruff check

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      # Checkout code from repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      # Add Poetry to PATH
      - name: Add Poetry to PATH
        run: |
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      # Install dependencies using Poetry
      - name: Install dependencies
        run: |
          poetry install --no-root

      # Run tests with pytest
      - name: Run tests with pytest
        env:
          PYTHONPATH: src
        run: |
          poetry run pytest
